### ISSUE TITLE
Fyrtur blind state

### ISSUE THREAD

**Issue by eggman0131** [Kane610/deconz#46]
Hi, 

I have a fyrtur blind in deconz.  It works fine, except whenever it's not 100% open the state reads as closed.  _I think_ it should be the other way around i.e the state should be open if the blind is not 100% closed.

Certainly that's how this card https://github.com/thomasloven/lovelace-slider-entity-row expects it to be.

I'm using home assistant 0.100.1 and deconz 2.05.69.

thanks

**Comment by Kane610** [comment]
Thanks for reporting!

I'm waiting for 2.05.70 before I will add my blinds to DECONZ. When I've done that I'll have a look at this

**Comment by eggman0131** [comment]
smashing, thanks

**Comment by ioangogo** [comment]
Annother thing is that due to how it is currently implemented controlling the blind through a on-network steering device or the buttons on the blind itself will not update the state of the blinds in home assistant.

Also, this issue is tangentially related as it affect the reporting of state where state information coming in on the websocket that isn't brightness is not updating the internal state of the device in home assistant, this is most evident when controlling the light through the light.turn_on service https://gfycat.com/madhardtofindhyrax

**Comment by eggman0131** [comment]
for anyone passing by with the same issue - I've been using a template cover as a workaround.  cover.kitchen_blind is the original blind entity from deconz.

This works fine and gives me full control over the position with voice commands (google home) and the gui, I use slider-entity-row.

```
cover:
  - platform: template
      template_kitchen_blind:
        friendly_name: "Kitchen Blind"
        open_cover:
          service: cover.open_cover
          data:
            entity_id: cover.kitchen_blind
        close_cover:
          service: cover.close_cover
          data:
            entity_id: cover.kitchen_blind
        set_cover_position:
          service: cover.set_cover_position
          data_template:
            entity_id: cover.kitchen_blind
            position: "{{ position }}"

        position_template: "{{ state_attr('cover.kitchen_blind', 'current_position') }}"
```
